services:
  ss-node:
    build: .
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network

  storage-node-1:
    build: .
    ports:
      - 8001:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-2:
    build: .
    ports:
      - 8002:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-3:
    build: .
    ports:
      - 8003:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-4:
    build: .
    ports:
      - 8004:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-5:
    build: .
    ports:
      - 8005:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-6:
    build: .
    ports:
      - 8006:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-7:
    build: .
    ports:
      - 8007:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-8:
    build: .
    ports:
      - 8008:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-9:
    build: .
    ports:
      - 8009:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-10:
    build: .
    ports:
      - 8010:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network

  storage-node-11:
    build: .
    ports:
      - 8011:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-12:
    build: .
    ports:
      - 8012:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-13:
    build: .
    ports:
      - 8013:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-14:
    build: .
    ports:
      - 8014:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-15:
    build: .
    ports:
      - 8015:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-16:
    build: .
    ports:
      - 8016:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-17:
    build: .
    ports:
      - 8017:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-18:
    build: .
    ports:
      - 8018:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-19:
    build: .
    ports:
      - 8019:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-20:
    build: .
    ports:
      - 8020:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  
  storage-node-21:
    build: .
    ports:
      - 8021:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-22:
    build: .
    ports:
      - 8022:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-23:
    build: .
    ports:
      - 8023:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-24:
    build: .
    ports:
      - 8024:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-25:
    build: .
    ports:
      - 8025:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-26:
    build: .
    ports:
      - 8026:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-27:
    build: .
    ports:
      - 8027:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-28:
    build: .
    ports:
      - 8028:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network

networks:
  ss-network:
    driver: bridge
