services:
  ss-node:
    build: .
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network

  storage-node-1:
    build: .
    ports:
      - 8001:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-2:
    build: .
    ports:
      - 8002:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-3:
    build: .
    ports:
      - 8003:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-4:
    build: .
    ports:
      - 8004:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-5:
    build: .
    ports:
      - 8005:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-6:
    build: .
    ports:
      - 8006:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-7:
    build: .
    ports:
      - 8007:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-8:
    build: .
    ports:
      - 8008:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-9:
    build: .
    ports:
      - 8009:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network
  storage-node-10:
    build: .
    ports:
      - 8010:8000
    expose:
      - 8000
    volumes:
      - ./src:/app
    networks:
      - ss-network

networks:
  ss-network:
    driver: bridge
